In [1]:
!pip install plotly

Requirement already satisfied: plotly in c:\users\bakru_b9pmn2k\anaconda3\lib\site-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\bakru_b9pmn2k\anaconda3\lib\site-packages (from plotly) (8.2.3)
Requirement already satisfied: packaging in c:\users\bakru_b9pmn2k\anaconda3\lib\site-packages (from plotly) (24.1)

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px

In [3]:
data = pd.read_csv("spotify_churn_dataset.csv")

In [4]:
data.head(2)

,user_id,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,1,Female,54,CA,Free,26,23,0.20,Desktop,31,0,1
1,2,Other,33,DE,Family,141,62,0.34,Web,0,1,0

In [70]:
data['subscription_type'] = data['subscription_type'].astype('category')

# Создаём график
fig = px.scatter(
    data,
    x='ads_listened_per_week',
    y='listening_time',
    color='subscription_type',
    title='Зависимость времени прослушивания от числа прослушанных рекламных вставок',
    size='songs_played_per_day',
    width=1500,
    height=1000,
    hover_data=['ads_listened_per_week', 'listening_time'],
    color_discrete_sequence=px.colors.qualitative.Set2  # фиксированная палитра
)


fig.show()

In [30]:
data.head(2)

,user_id,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,1,Female,54,CA,Free,26,23,0.20,Desktop,31,0,1
1,2,Other,33,DE,Family,141,62,0.34,Web,0,1,0

In [43]:
fig = px.bar(
    data, 
    x='subscription_type',                       
    color='device_type',  
    title='распределение по типу подписки (и типу устройства)',
    labels={'city': 'Город', 'sales': 'Сумма продаж'}, 
    barmode='group',
    color_discrete_sequence=px.colors.qualitative.Set1
)

fig.show()

In [42]:
data.head(2)

,user_id,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,1,Female,54,CA,Free,26,23,0.20,Desktop,31,0,1
1,2,Other,33,DE,Family,141,62,0.34,Web,0,1,0

In [51]:
fig = px.treemap(
    data,
    path=['is_churned', 'country'], 
    values='skip_rate', 
    
    color='skip_rate', 
    
    title='СУММАРНЫЙ skip_rate по оттоку и стране, раскрашенный по СРЕДНЕМУ skip_rate',
    
    color_continuous_scale=px.colors.sequential.Viridis, 
    
    hover_data=['is_churned'] 
)

fig.show()

In [52]:
data.head(2)

,user_id,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,1,Female,54,CA,Free,26,23,0.20,Desktop,31,0,1
1,2,Other,33,DE,Family,141,62,0.34,Web,0,1,0

In [69]:
fig_scatter = px.scatter(
    data, 
    x='songs_played_per_day', 
    y='listening_time', 

    width=1500,
    height=1000,

    color='is_churned',

    title='Точечный график: Песни vs. Время, раскрашенные по факту оттока',
    color_continuous_scale=px.colors.sequential.Bluered, 
)

fig_scatter.show()

In [72]:
data.head(2)

,user_id,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,1,Female,54,CA,Free,26,23,0.20,Desktop,31,0,1
1,2,Other,33,DE,Family,141,62,0.34,Web,0,1,0

In [ ]:
fig = px.violin(
    data,
    y='songs_played_per_day',        
    color='gender', 
    
    facet_col='subscription_type', 
    facet_col_wrap=2,

    height=600, 
    
    box=True,                        
    points="all",                    
    hover_data=['age', 'listening_time', 'skip_rate'],
    
    title='Распределение проигранных песен по полу, с разбивкой по типу подписки',
    labels={
        'songs_played_per_day': 'Песен проиграно в день',
        'gender': 'Пол'
    }
)

fig.show()