In [5]:
from qr_eigenvalues import tridiagonalize_householder, qr_eigenvalues
import numpy as np
import pandas as pd


def print_res(A_input: np.ndarray):
    A_tridiagonal = tridiagonalize_householder(A_input.copy())
    res = qr_eigenvalues(A_tridiagonal, 1e-10)
    
    print("Исходная матрица:")
    display(pd.DataFrame(A_input))  

    print("\nТрехдиагональная матрица:")
    display(pd.DataFrame(np.round(A_tridiagonal, 4))) 

    print("\nСобственные значения:")
    display(pd.DataFrame(sorted(res), columns=["Собственные значения"]))  

def check_with_numpy(A):
    eig_np = np.linalg.eigvals(A)
    eig_np = np.sort(eig_np)

    print("NumPy:")
    print(eig_np)

A1 = np.array([
    [-1,  3,  3],
    [ 3,  5,  0],
    [ 3,  0, -1]
], dtype='float')

A2 = np.array([
    [ 4,  5,  5,  4,  2, -5, -2],
    [ 5, -1, -5, -2,  2,  0,  2],
    [ 5, -5, -3, -1,  2,  0, -5],
    [ 4, -2, -1,  2,  1, -3, -2],
    [ 2,  2,  2,  1,  3, -5,  4],
    [-5,  0,  0, -3, -5, -3, -4],
    [-2,  2, -5, -2,  4, -4, -5]
], dtype='float')

A3 = np.array([
    [-2,  3,  5, -3, -2, -4, -2,  3,  3, -5, -1,  2, -2, -3,  5],
    [ 3, -1,  4,  4, -5, -1, -3,  0,  2,  4,  0, -3, -2,  5, -1],
    [ 5,  4, -2, -4, -1,  5,  1,  4,  1,  1, -1, -2, -3,  5,  5],
    [-3,  4, -4,  4,  4, -2, -5, -1,  0, -1, -1, -4, -5,  3,  5],
    [-2, -5, -1,  4, -3,  0, -1, -2,  5,  3,  5,  5, -1, -4,  4],
    [-4, -1,  5, -2,  0,  0,  5, -5,  1,  5,  5,  5,  3,  4,  2],
    [-2, -3,  1, -5, -1,  5, -2, -4,  0, -1,  3,  4,  4, -3,  2],
    [ 3,  0,  4, -1, -2, -5, -4, -4, -2, -3,  5,  2, -4, -2,  2],
    [ 3,  2,  1,  0,  5,  1,  0, -2, -4, -1, -5,  5,  4,  2, -2],
    [-5,  4,  1, -1,  3,  5, -1, -3, -1,  0, -3, -5, -3, -5, -1],
    [-1,  0, -1, -1,  5,  5,  3,  5, -5, -3,  5, -4, -2, -4, -5],
    [ 2, -3, -2, -4,  5,  5,  4,  2,  5, -5, -4, -2,  5,  0,  5],
    [-2, -2, -3, -5, -1,  3,  4, -4,  4, -3, -2,  5,  0,  4,  3],
    [-3,  5,  5,  3, -4,  4, -3, -2,  2, -5, -4,  0,  4,  5,  5],
    [ 5, -1,  5,  5,  4,  2,  2,  2, -2, -1, -5,  5,  3,  5, -3]
], dtype='float')

In [6]:
print_res(A1)
check_with_numpy(A1)

Исходная матрица:

     0    1    2
0 -1.0  3.0  3.0
1  3.0  5.0  0.0
2  3.0  0.0 -1.0

Трехдиагональная матрица:

        0       1    2
0 -1.0000 -4.2426  0.0
1 -4.2426  2.0000  3.0
2  0.0000  3.0000  2.0

Собственные значения:

   Собственные значения
0             -4.510259
1              1.066677
2              6.443583

NumPy:
[-4.51025946  1.06667655  6.44358291]

In [7]:
print_res(A2)
check_with_numpy(A2)

Исходная матрица:

     0    1    2    3    4    5    6
0  4.0  5.0  5.0  4.0  2.0 -5.0 -2.0
1  5.0 -1.0 -5.0 -2.0  2.0  0.0  2.0
2  5.0 -5.0 -3.0 -1.0  2.0  0.0 -5.0
3  4.0 -2.0 -1.0  2.0  1.0 -3.0 -2.0
4  2.0  2.0  2.0  1.0  3.0 -5.0  4.0
5 -5.0  0.0  0.0 -3.0 -5.0 -3.0 -4.0
6 -2.0  2.0 -5.0 -2.0  4.0 -4.0 -5.0

Трехдиагональная матрица:

        0       1       2       3       4       5       6
0  4.0000 -9.9499  0.0000  0.0000  0.0000  0.0000  0.0000
1 -9.9499 -2.2727 -6.7147  0.0000  0.0000  0.0000  0.0000
2  0.0000 -6.7147  2.1607  4.2023  0.0000  0.0000  0.0000
3  0.0000  0.0000  4.2023 -3.2619  7.0350  0.0000  0.0000
4  0.0000  0.0000  0.0000  7.0350 -0.7748 -5.5258  0.0000
5  0.0000  0.0000  0.0000  0.0000 -5.5258 -4.6300 -0.9439
6  0.0000  0.0000  0.0000  0.0000  0.0000 -0.9439  1.7788

Собственные значения:

   Собственные значения
0            -12.763141
1            -10.907107
2             -4.752937
3              1.781824
4              2.905488
5              7.544653
6             13.191221

NumPy:
[-12.76314081 -10.90710738  -4.75293654   1.78182388   2.90548751
   7.54465277  13.19122057]

In [8]:
print_res(A3)

Исходная матрица:

     0    1    2    3    4    5    6    7    8    9    10   11   12   13   14
0  -2.0  3.0  5.0 -3.0 -2.0 -4.0 -2.0  3.0  3.0 -5.0 -1.0  2.0 -2.0 -3.0  5.0
1   3.0 -1.0  4.0  4.0 -5.0 -1.0 -3.0  0.0  2.0  4.0  0.0 -3.0 -2.0  5.0 -1.0
2   5.0  4.0 -2.0 -4.0 -1.0  5.0  1.0  4.0  1.0  1.0 -1.0 -2.0 -3.0  5.0  5.0
3  -3.0  4.0 -4.0  4.0  4.0 -2.0 -5.0 -1.0  0.0 -1.0 -1.0 -4.0 -5.0  3.0  5.0
4  -2.0 -5.0 -1.0  4.0 -3.0  0.0 -1.0 -2.0  5.0  3.0  5.0  5.0 -1.0 -4.0  4.0
5  -4.0 -1.0  5.0 -2.0  0.0  0.0  5.0 -5.0  1.0  5.0  5.0  5.0  3.0  4.0  2.0
6  -2.0 -3.0  1.0 -5.0 -1.0  5.0 -2.0 -4.0  0.0 -1.0  3.0  4.0  4.0 -3.0  2.0
7   3.0  0.0  4.0 -1.0 -2.0 -5.0 -4.0 -4.0 -2.0 -3.0  5.0  2.0 -4.0 -2.0  2.0
8   3.0  2.0  1.0  0.0  5.0  1.0  0.0 -2.0 -4.0 -1.0 -5.0  5.0  4.0  2.0 -2.0
9  -5.0  4.0  1.0 -1.0  3.0  5.0 -1.0 -3.0 -1.0  0.0 -3.0 -5.0 -3.0 -5.0 -1.0
10 -1.0  0.0 -1.0 -1.0  5.0  5.0  3.0  5.0 -5.0 -3.0  5.0 -4.0 -2.0 -4.0 -5.0
11  2.0 -3.0 -2.0 -4.0  5.0  5.0  4.0  2.0  5.0 -5.0 -4.0 -2.0  5.0  0.0  5.0
12 -2.0 -2.0 -3.0 -5.0 -1.0  3.0  4.0 -4.0  4.0 -3.0 -2.0  5.0  0.0  4.0  3.0
13 -3.0  5.0  5.0  3.0 -4.0  4.0 -3.0 -2.0  2.0 -5.0 -4.0  0.0  4.0  5.0  5.0
14  5.0 -1.0  5.0  5.0  4.0  2.0  2.0  2.0 -2.0 -1.0 -5.0  5.0  3.0  5.0 -3.0

Трехдиагональная матрица:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,-2.0000,-12.3693,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,-12.3693,0.0131,9.6301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,0.0000,9.6301,-5.5946,10.3232,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,0.0000,0.0000,10.3232,5.3536,11.8495,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,0.0000,0.0000,0.0000,11.8495,-1.9741,-10.3935,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
5,0.0000,0.0000,0.0000,0.0000,-10.3935,-4.1460,9.6898,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
6,0.0000,0.0000,0.0000,0.0000,0.0000,9.6898,-2.2925,10.0796,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
7,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,10.0796,4.1085,-15.0070,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
8,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,-15.0070,1.2365,-5.1387,0.0000,0.0000,0.0000,0.0000,0.0000
9,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,-5.1387,-0.0978,5.6692,0.0000,0.0000,0.0000,0.0000
10,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,5.6692,4.0656,-7.8060,0.0000,0.0000,0.0000
11,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,-7.8060,-1.4724,3.2329,0.0000,0.0000
12,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,3.2329,-8.3625,-2.9272,0.0000
13,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,-2.9272,8.1973,-1.4416
14,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,-1.4416,-6.0346

Собственные значения:

    Собственные значения
0             -21.644561
1             -18.889142
2             -14.864205
3             -11.080426
4              -8.930496
5              -6.633485
6              -6.114390
7              -3.116403
8               0.531295
9               6.808621
10              8.832795
11             11.685277
12             13.328363
13             19.487776
14             21.598982